Vagrant.configure("2") do |config|
  config.vm.box = "envimation/ubuntu-xenial"

  config.vm.network "private_network", ip: "192.168.33.16"

  config.vm.network "forwarded_port", guest: 80, host: 8080 # Apache
  config.vm.network "forwarded_port", guest: 3306, host: 3306 # MySQL

  # Forward the SSH port from the guest machine to the host machine
  config.vm.network "forwarded_port", guest: 22, host: 2222

  # Install Apache
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2
  SHELL

  # Install PHP 5.6
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update
    sudo apt-get install -y php5.6
  SHELL

  # Install MySQL
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y mysql-server
  SHELL

  config.vm.synced_folder "./app", "/var/www/html"
end
