Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", ip: "192.168.33.16"

#   config.vm.provider "virtualbox" do |vb|
#     # Enable the GUI
#     vb.gui = true
#   end

  config.vm.network "forwarded_port", guest: 80, host: 8080 # Apache
  config.vm.network "forwarded_port", guest: 3306, host: 3306 # MySQL

  # Install Apache
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2
  SHELL

  # Install PHP 5.6
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update
    sudo apt-get install -y php5.6
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # Install PDO drivers for MySQL, PostgreSQL, and SQLite
    sudo apt-get install -y php5.6-mysql php5.6-pgsql php5.6-sqlite3

    # Install DOM, HtmlPurifier, and CWsdlGenerator
    sudo apt-get install -y php5.6-dom php5.6-htmlpurifier php5.6-soap

    # Install Memcache and APC
    sudo apt-get install -y php5.6-memcache php5.6-apcu

    # Install SOAP, Mcrypt, and GD/ImageMagick
    sudo apt-get install -y php5.6-soap php5.6-mcrypt php5.6-gd imagemagick

    # Enable the extensions
    sudo phpenmod pdo_mysql pdo_pgsql pdo_sqlite dom htmlpurifier soap memcache apcu mcrypt gd imagick

    # Restart Apache to apply the changes
    sudo service apache2 restart
  SHELL

  # Install MySQL
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y mysql-server
  SHELL

  config.vm.synced_folder "./app", "/var/www/html"
end
